FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=letmein
ENV N8N_HOST=localhost
ENV N8N_PORT=5678
ENV GENERIC_TIMEZONE=Asia/Kolkata

EXPOSE 5678

CMD ["n8n"]
